### ISSUE TITLE
Possible Data loss

### ISSUE THREAD

**Issue by jwbranch3i** [sjhaddad/CSC-289---Capstone-Project---Group-13#17]
In info edit
possible to lose information if there is a program interruption
before option '6.Exit' is selected.

**Comment by Shawn-1992** [comment]
So if we're envisioning the edit user menu in the finished web application, I imagine it would look something like the attached image. If a user enters info, it has to be submitted to be stored. If they exit, or the program crashes before submitting, they will have to redo their edit. In the current version of the edit UI, selecting 6 is the equivalent to a submit button. 
![edit_profile](https://github.com/sjhaddad/CSC-289---Capstone-Project---Group-13/assets/146864289/48fc7927-5c61-45c8-8076-5bbbd508d49c)
