### ISSUE TITLE
Main.py structure, getters and setters for user class, edit user option

### ISSUE THREAD

**Issue by jwbranch3i** [sjhaddad/CSC-289---Capstone-Project---Group-13#2]
1. Place each option in main menu into its own function this way
   we are able to write unit test for each option.
   
2. Need setters and getters for user class

3. Option 2, -Edit user income by name-, doesn't find and change
   an existing user object.

**Comment by bryancramsey** [comment]
1. Solved
2. Solved
3. So technically, what I believe it does is it creates a new user object that has the identical name to the user we want to change in the table, and then uses that to provide the necessary information to find and update the user in the table. The table itself doesn't actually store an object, it just stores fields that represent the information we feed it through objects. I could be incorrect in this understanding though.
