### ISSUE TITLE
Negative income

### ISSUE THREAD

**Issue by jwbranch3i** [sjhaddad/CSC-289---Capstone-Project---Group-13#21]
If negative income is entered when generating tax it is flaged by the program
as not being valid but it is still saved in the table,
do we want this?  When displaying all information if income is negative in
table income tax displayed will be negative.

**Comment by Shawn-1992** [comment]
I believe the negative input being displayed was from tax reports generated prior to implementing the input validation. I don't think invalid input will be displayed anymore.
