### ISSUE TITLE
Question about total_income

### ISSUE THREAD

**Issue by jwbranch3i** [sjhaddad/CSC-289---Capstone-Project---Group-13#25]
Is total_income in the database suppose to be the total income entered when generating a tax estimate 
or is it the adjusted income after applying the deductible.

Now the adjusted income is being saved and there is no record of the total income.

**Comment by Shawn-1992** [comment]
adjusted income is supposed to be total income after applying deductible. table has been updated so both total and adjusted can be saved and dispalyed
